In [1]:
import os
import numpy as np 
import pandas as pd 

In [37]:
os.chdir("D:/Imarticus/Supervised Learning/SVM/Data shared by pranjal sir/1")
mp=pd.read_csv("D:/Imarticus/Supervised Learning/SVM/Data shared by pranjal sir/1/trainRF.csv")
mp

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
mp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [4]:
mp.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
mp_train,mp_test=train_test_split(mp,test_size=.2)

In [7]:
mp_train_x=mp_train.iloc[:,0:-1]
mp_train_y=mp_train.iloc[:,-1]

In [8]:
mp_test_x=mp_test.iloc[:,0:-1]
mp_test_y=mp_test.iloc[:,-1]

In [9]:
from sklearn.svm import SVC

## Checking the best kernel

In [27]:
svc=SVC()

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[100,   3,   0,   0],
       [  0, 100,   9,   0],
       [  0,   4,  81,   3],
       [  0,   0,   5,  95]], dtype=int64)

In [28]:
tab.diagonal().sum()/tab.sum() # It tells us the accuracy of the Model

0.94

### Let use Linear kernal 

In [29]:
svc=SVC(kernel='linear')

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[100,   1,   0,   0],
       [  0, 105,   5,   0],
       [  0,   1,  88,   1],
       [  0,   0,   2,  97]], dtype=int64)

In [30]:
tab.diagonal().sum()/tab.sum()

0.975

### Lets use Sigmoid

In [31]:
svc=SVC(kernel='sigmoid')

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[59,  3,  2, 21],
       [ 0,  5, 17, 71],
       [ 0,  0,  0,  0],
       [41, 99, 76,  6]], dtype=int64)

In [32]:
tab.diagonal().sum()/tab.sum()

0.175

### Let use Polynomial ( we need to add or change  degree here )

In [33]:
svc=SVC(kernel='poly') # Here default degree is 3 

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[100,   4,   0,   0],
       [  0, 101,   8,   0],
       [  0,   2,  84,   4],
       [  0,   0,   3,  94]], dtype=int64)

In [34]:
tab.diagonal().sum()/tab.sum()

0.9475

### Changing the degree of poly

In [35]:
svc=SVC(kernel='poly',degree=2) 

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[100,   4,   0,   0],
       [  0, 100,   7,   0],
       [  0,   3,  85,   5],
       [  0,   0,   3,  93]], dtype=int64)

In [36]:
tab.diagonal().sum()/tab.sum()

0.945

### Note:- Let's use grid search for best kernal selection 