In [1]:
import os
import numpy as np 
import pandas as pd 

In [13]:
os.chdir("D:/Imarticus/Supervised Learning/SVM/Data shared by pranjal sir/2")
mp=pd.read_csv("D:/Imarticus/Supervised Learning/SVM/Data shared by pranjal sir/2/svmfile.csv")
mp

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [14]:
mp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [15]:
mp.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [61]:
mp.loc[mp['y']=='no','y']=0

In [62]:
mp.loc[mp['y']=='yes','y']=1

In [63]:
mp.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   56    3        1          0        0        0     0        1      6   
1   57    7        1          3        1        0     0        1      6   
2   37    7        1          3        0        2     0        1      6   
3   40    0        1          1        0        0     0        1      6   
4   56    7        1          3        0        0     2        1      6   

   day_of_week  ...  campaign  pdays  previous  poutcome  emp.var.rate  \
0            1  ...         1    999         0         1           1.1   
1            1  ...         1    999         0         1           1.1   
2            1  ...         1    999         0         1           1.1   
3            1  ...         1    999         0         1           1.1   
4            1  ...         1    999         0         1           1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0          93.994          -36.4      4.857       5191.0  0  
1          93.994          -36.4      4.857       5191.0  0  
2          93.994          -36.4      4.857       5191.0  0  
3          93.994          -36.4      4.857       5191.0  0  
4          93.994          -36.4      4.857       5191.0  0  

[5 rows x 21 columns]

In [64]:
categorical_col = mp.select_dtypes(include=['object']).columns
categorical_col

Index([], dtype='object')

In [65]:
from sklearn.preprocessing import LabelEncoder

In [66]:
df_cat=mp[['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome']]

In [67]:
for c in df_cat:
    lbl=LabelEncoder()
    lbl.fit(list(mp[c].values))
    mp[c]=lbl.transform(list(mp[c].values))

## But In Label Encoder we cannot control the value assign to the variable.

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
mp_train,mp_test=train_test_split(mp,test_size=.2)

In [70]:
mp_train_x=mp_train.iloc[:,0:-1]
mp_train_y=mp_train.iloc[:,-1]

In [71]:
mp_train_x.head()

age  job  marital  education  default  housing  loan  contact  month  \
33730   53    1        1          1        1        2     0        0      6   
36302   32    0        2          6        0        2     0        0      4   
32449   35    4        1          5        0        1     1        0      6   
31539   32    1        1          2        0        2     0        0      6   
8774    37    0        1          6        0        0     0        1      4   

       day_of_week  duration  campaign  pdays  previous  poutcome  \
33730            4       659         1    999         0         1   
36302            1       253         1    999         0         1   
32449            0       154         3    999         1         0   
31539            2       413         1    999         0         1   
8774             2        63         1    999         0         1   

       emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed  
33730          -1.8          92.893          -46.2      1.281       5099.1  
36302          -2.9          92.963          -40.8      1.266       5076.2  
32449          -1.8          92.893          -46.2      1.313       5099.1  
31539          -1.8          92.893          -46.2      1.327       5099.1  
8774            1.4          94.465          -41.8      4.866       5228.1

In [72]:
mp_train_y.head()

33730    1
36302    1
32449    0
31539    0
8774     0
Name: y, dtype: int64

In [73]:
mp_test_x=mp_test.iloc[:,0:-1]
mp_test_y=mp_test.iloc[:,-1]

In [74]:
from sklearn.svm import SVC

## Checking the best kernel

In [75]:
svc=SVC()

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

In [77]:
tab.diagonal().sum()/tab.sum() # It tells us the accuracy of the Model

0.8882010196649672

### Let use Linear kernal 

In [78]:
svc=SVC(kernel='linear')

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[6935,  551],
       [ 312,  440]], dtype=int64)

In [79]:
tab.diagonal().sum()/tab.sum()

0.895241563486283

### Lets use Sigmoid

In [80]:
svc=SVC(kernel='sigmoid')

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[7138,  808],
       [ 109,  183]], dtype=int64)

In [81]:
tab.diagonal().sum()/tab.sum()

0.8886865744112649

### Let use Polynomial ( we need to add or change  degree here )

In [82]:
svc=SVC(kernel='poly') # Here default degree is 3 

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[7136,  809],
       [ 111,  182]], dtype=int64)

In [83]:
tab.diagonal().sum()/tab.sum()

0.8883224083515416

### Changing the degree of poly

In [84]:
svc=SVC(kernel='poly',degree=2) 

svc.fit(mp_train_x,mp_train_y)

pred_svc=svc.predict(mp_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,mp_test_y)

tab

array([[7138,  812],
       [ 109,  179]], dtype=int64)

In [85]:
tab.diagonal().sum()/tab.sum()

0.8882010196649672

Class imbalance is a problem. 

Where representation of one class Or one category is much more than another. 

Solution to class imbalance
1. over samplings or Up sampling
* In this we will increase the representation of the class which is under represented. 

2. Under sampling or Down sampling 
* In this we will decrease the records or representation of the class which is over represented.

Os and US has to be only on done train data

### Task :- Let's use grid search for best kernal selection 

## OverSampling & UnderSampling

### Here we try to increase the 1 values in the target variable.

In [88]:
bd_train,bd_test=train_test_split(mp,test_size=.2)

In [91]:
bd_train.y.value_counts()

0    29210
1     3740
Name: y, dtype: int64

In [89]:
bd_train.shape

(32950, 21)

In [93]:
df1=bd_train[bd_train.y==1]

In [94]:
bd_train1=pd.concat([bd_train,df1,df1,df1,df1,df1])

In [95]:
bd_train1.y.value_counts()

0    29210
1    22440
Name: y, dtype: int64

In [97]:
bd_train_x=bd_train1.iloc[:,0:-1]
bd_train_y=bd_train1.iloc[:,-1]

In [98]:
bd_test_x=bd_test.iloc[:,0:-1]
bd_test_y=bd_test.iloc[:,-1]

# I will not make any changes over here (test)

### Again Checking with the kernel

In [99]:
svc=SVC()

svc.fit(bd_train_x,bd_train_y)

pred_svc=svc.predict(bd_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,bd_test_y)

tab

array([[6376,  189],
       [ 962,  711]], dtype=int64)

In [100]:
tab.diagonal().sum()/tab.sum()

0.8602816217528526

In [101]:
svc=SVC(kernel='linear')

svc.fit(bd_train_x,bd_train_y)

pred_svc=svc.predict(bd_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,bd_test_y)

tab

array([[5712,   70],
       [1626,  830]], dtype=int64)

In [102]:
tab.diagonal().sum()/tab.sum()

0.7941247875697985

In [103]:
svc=SVC(kernel='sigmoid')

svc.fit(bd_train_x,bd_train_y)

pred_svc=svc.predict(bd_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,bd_test_y)

tab

array([[6129,  422],
       [1209,  478]], dtype=int64)

In [104]:
tab.diagonal().sum()/tab.sum()

0.8020150521971352

In [105]:
svc=SVC(kernel='poly')

svc.fit(bd_train_x,bd_train_y)

pred_svc=svc.predict(bd_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,bd_test_y)

tab

array([[6358,  181],
       [ 980,  719]], dtype=int64)

In [106]:
tab.diagonal().sum()/tab.sum()

0.8590677348871085

In [107]:
svc=SVC(kernel='poly',degree=2)

svc.fit(bd_train_x,bd_train_y)

pred_svc=svc.predict(bd_test_x)

from sklearn.metrics import confusion_matrix
tab=confusion_matrix(pred_svc,bd_test_y)

tab

array([[6390,  184],
       [ 948,  716]], dtype=int64)

In [108]:
tab.diagonal().sum()/tab.sum()

0.8625880067977665